### ISSUE TITLE
Mail-In Ballot Support

### ISSUE THREAD

**Issue by CodeOtter** [microsoft/electionguard-ballot-marking-device#7]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I'd like to see if the ElectionGuard team at Microsoft has been anticipating how to handle mail-in ballots given our current pandemic situation.

**Describe the solution you'd like**

I see a Print feature has been added (https://github.com/microsoft/electionguard-ballot-marking-device/blob/master/src/pages/PrintPage.tsx#L228) and that you are supporting the Chaum-Pedersen Protocol (https://github.com/microsoft/electionguard-verifier/blob/master/src/crypto/chaum_pedersen.rs#L12)  and several others to counter any implementation or shortcomings each public secret sharing/encryption technique has.  This is a useful way to ensure the authenticity of the chain of custody regarding an election process.  Tracking voters confirmation that their vote has been processed can be a preliminary way to ward off people who are looking to illegally use mail-in votes to, for example, use bad social security numbers or submitting on behalf of an absentee voter.

**Describe alternatives you've considered**
I've not seen much in terms of ensuring homomorphic encrypted results ensuring the integrity of mail-in ballots, so I have nothing terms of alternatives.

**Teachability, Documentation, Adoption, Migration Strategy**
![mailin](https://user-images.githubusercontent.com/2237846/78953122-a4603500-7a8c-11ea-9589-82b28b9c541a.png)

**Comment by rc-ms** [comment]
Hi there,

Thanks for your interest, but I confess I'm unclear about the ask / issue. Can you elaborate?
